### ISSUE TITLE
[Question] Presto manager vs presto admin

### ISSUE THREAD

**Issue by satybald** [prestodb/presto-manager#68]
While browsing a `prestodb` org I accidentally found your project. Looks like the project relatively young and there's not much documentation about it. I'm wondering what's the difference between `presto-manager` and [presto-admin](https://prestodb.io/presto-admin/docs/current/index.html)? Is there any user documentation for the project?

**Comment by petroav** [comment]
`presto-manager` is supposed to eventually replace `presto-admin`. There's no documentation other than what is present in the project. `presto-manager` is still very much in development, lacking some basic functionality so it's not recommended for users at the moment.

**Comment by satybald** [comment]
thanks for reply @petroav! but could you say what's the reason behind this move? :smile: what functionality `presto-manager` expects to enhance or add?

**Comment by petroav** [comment]
@satybald -- the decision to start presto-manager was not feature driven but more architecture/refactor driven. While `presto-admin` is a great tool, its design and architecture are a little flawed: it is difficult to test end to end (we rely on Docker containers and the infrastructure around those tests is a nightmare), relies on passwordless SSH to be setup on the cluster and is difficult to extend because of the increased testing burden.

`presto-manager`'s design is inspired by Presto -- it is a single JVM process that will run on every node; all communication will happen over HTTP and there will be a REST interface that clients can interact with. This will greatly simplify correctness testing and allow users to write clients (CLI and GUI based) against the REST interface. Hopefully this will also enable us to more easily add more advanced features like HA and cluster re-sizing.

**Comment by satybald** [comment]
@petroav now I got it. thanks for the information.
